./vsrc/bcd_counter.v
./vsrc/ps2_keyboard.v
./vsrc/bcd2seg.v
./vsrc/top.v
./vsrc/key_disp_fsm.v
./vsrc/seq_detector.v
./vsrc/keycode2ascii.v
./vtb/keyboard_sim.v
./vtb/ps2_keyboard_model.v
./vtb/testbench.v
./vtb/seq_detector_tb.v
